### PR TITLE
Now date time picker shows the date using user's current locale

### PR DESCRIPTION
**Pull request by mgtitimoli**
Hi @cnjon,

I was using the component and I got stuck with the necessity of showing the date and time using the user current locale. This PR enables this feature.

When you have some time, could you please have a look to it?

Thanks!

### CODE REVIEW

**Comment by cnjon** [comment]
@mgtitimoli This PR has conflicts,please fix it and recommit,thank you very much!

**Comment by mgtitimoli** [comment]
Hi @cnjon,

I have fixed the conflicts.

Could you please let me know when you are able to upload the latest to npm?

Thanks!

**Comment by cnjon** [comment]
@mgtitimoli Thanks!
i will upload the latest to npm today!

**Comment by mgtitimoli** [comment]
Thanks @cnjon! I've just updated the version to 0.1.0, it looks great!

**Pull request merged**
